steps:
- pwsh: |
    $ErrorActionPreference = 'Stop'
    $ErrorView = 'NormalView'
    $VerbosePreference = 'Continue'
    "PUBLISH_DRYRUN: '$($env:PUBLISH_DRYRUN)'" | Write-Verbose
    Import-Module .\build\PSModulePublisher\src\PSModulePublisher\PSModulePublisher.psm1 -Force -Verbose
    Invoke-Publish -Repository 'PSGallery' -DryRun:$([System.Convert]::ToBoolean($env:PUBLISH_DRYRUN))
  displayName: Publish module
  env:
    NUGET_API_KEY: $(NUGET_API_KEY)
