name: ci-master-pr

on:
  push:
    branches:
    - master
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test-powershell-5_1-windows-2022:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        powershell -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Install PSModulePublisher
      run: |
        powershell -NoLogo -NonInteractive -NoProfile -Command 'Install-Module -Name PSModulePublisher -Repository PSGallery -Scope CurrentUser -Force -Verbose'
    - name: Generate module manifest
      run: |
        # Process applicable environment variables
        export MODULE_VERSION=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/v(.*)/\1/p' )
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Build (Generates module manifest)
        powershell -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Build'
    - name: Test module via module manifest
      run: |
        # Process applicable environment variables
        export MODULE_VERSION=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/v(.*)/\1/p' )
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Test (Tests module via module manifest)
        powershell -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Test'

  test-powershell-core-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Install PSModulePublisher
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command 'Install-Module -Name PSModulePublisher -Repository PSGallery -Scope CurrentUser -Force -Verbose'
    - name: Generate module manifest
      run: |
        # Process applicable environment variables
        export MODULE_VERSION=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/v(.*)/\1/p' )
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Build (Generates module manifest)
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Build'
    - name: Test module via module manifest
      run: |
        # Process applicable environment variables
        export MODULE_VERSION=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/v(.*)/\1/p' )
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Test (Tests module via module manifest)
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Test'

  test-build_publish-powershell-5_1-windows-2022:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        powershell -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Install PSModulePublisher
      run: |
        powershell -NoLogo -NonInteractive -NoProfile -Command 'Install-Module -Name PSModulePublisher -Repository PSGallery -Scope CurrentUser -Force -Verbose'
    - name: Generate module manifest
      run: |
        # Process applicable environment variables
        export MODULE_VERSION='999.0.0'
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Build (Generates module manifest)
        powershell -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Build'
    - name: Publish module (Dry run)
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        # Process applicable environment variables
        export MODULE_VERSION='999.0.0'
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Publish (Publishes module with -WhatIf)
        powershell -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Publish -Repository PSGallery -DryRun'

  build_publish-powershell-5_1-windows-2022:
    needs:
      - test-powershell-5_1-windows-2022
      - test-powershell-core-windows
      - test-build_publish-powershell-5_1-windows-2022
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        powershell -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Install PSModulePublisher
      run: |
        powershell -NoLogo -NonInteractive -NoProfile -Command 'Install-Module -Name PSModulePublisher -Repository PSGallery -Scope CurrentUser -Force -Verbose'
    - name: Generate module manifest
      shell: bash
      run: |
        # Process applicable environment variables
        export MODULE_VERSION=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/v(.*)/\1/p' )
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Build (Generates module manifest)
        powershell -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Build'
    - name: Publish module
      if: startsWith(github.ref, 'refs/tags/')
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      shell: bash
      run: |
        # Process applicable environment variables
        export MODULE_VERSION=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/v(.*)/\1/p' )
        export MODULE_NAME=$( basename "$( git rev-parse --show-toplevel )" )

        # Publish (Publishes module)
        powershell -NoLogo -NonInteractive -NoProfile -Command '$VerbosePreference = "Continue"; Invoke-Publish -Repository PSGallery'
