trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: myserviceconnection                   # Check for your 'Type: Github' connection under 'Project Settings' > 'Service connections'
    ref: refs/tags/vx.x.x

stages:
- stage: build_test
  displayName: Build, Test
  jobs:
  - job: linux
    displayName: '[Linux] PowerShell Core'
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/build-test.yml@PSModulePublisher
  - job: windows_powershell_core
    displayName: '[Windows] PowerShell Core'
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/build-test.yml@PSModulePublisher
- stage: build_publish
  displayName: Build, Publish
  dependsOn: build_test
  jobs:
  - job: linux
    displayName: '[Linux] PowerShell Core'
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/build-publish.yml@PSModulePublisher
