trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: myserviceconnection                   # Check for your 'Type: Github' connection under 'Project Settings' > 'Service connections'
    ref: refs/tags/vx.x.x

stages:
- stage: build_test
  displayName: Build, Test
  jobs:
  - job: linux_container
    displayName: '[Linux] [Container] PowerShell'
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        7.4.2:
          containerImage: joeltimothyoh/powershell:7.4.2-ubuntu-22.04-git-sudo
        7.3.9:
          containerImage: joeltimothyoh/powershell:7.3.9-ubuntu-22.04-git-sudo
        7.2.2:
          containerImage: joeltimothyoh/powershell:7.2.2-ubuntu-20.04-git-sudo
        7.1.5:
          containerImage: joeltimothyoh/powershell:7.1.5-ubuntu-20.04-git-sudo
        7.0.3:
          containerImage: joeltimothyoh/powershell:7.0.3-ubuntu-18.04-git-sudo
        6.2.4:
          containerImage: joeltimothyoh/powershell:6.2.4-ubuntu-18.04-git-sudo
        6.1.3:
          containerImage: joeltimothyoh/powershell:6.1.3-ubuntu-18.04-git-sudo
    container: $[ variables['containerImage'] ]
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/build-test.yml@PSModulePublisher
- stage: build_publish
  displayName: Build, Publish
  dependsOn: build_test
  jobs:
  - job: linux
    displayName: '[Linux] PowerShell Core'
    pool:
      vmImage: ubuntu-22.04
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/build-publish.yml@PSModulePublisher
