trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: myserviceconnection                   # Check for your 'Type: Github' connection under 'Project Settings' > 'Service connections'
    ref: refs/tags/vx.x.x

stages:
- stage: build_test_publish
  displayName: Build, Test, Publish
  jobs:
  - job: windows_powershell_core
    displayName: '[Windows] PowerShell Core'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/build-test.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/windows/publish.yml@PSModulePublisher
