steps:
- powershell: |
    $ErrorActionPreference = 'Stop'
    $ErrorView = 'NormalView'
    $VerbosePreference = 'Continue'
    Import-Module .\src\PSModulePublisher\PSModulePublisher.psm1 -Force -Verbose
    $MODULE_MANIFEST_PATH = Invoke-Build
    ### Begin CI-specific code: Set job-scoped variables
    echo "##vso[task.setvariable variable=MODULE_MANIFEST_PATH]${MODULE_MANIFEST_PATH}"
    ### End of CI-specific code
  displayName: Generate module manifest
